name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.5.1"

      - name: Clear node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: List installed packages
        run: npm list

      - name: Build the project
        run: npm run build

      - name: Transfer project files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "./*"
          target: "/app/dictation-studio-ui"
          rm: true

      - name: Transfer build artifacts to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "dist/*"
          target: "/app/dictation-studio-ui/dist"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /app/dictation-studio-ui
            npm install --production
            pm2 stop dictation-studio-ui || true
            pm2 delete dictation-studio-ui || true
            pm2 start npm --name dictation-studio-ui -- start
